export const initialValues = {
	title: '',
	text: '',
	backgroundColor: '#ffffff',
	titleColor: '#000000',
	textColor: '#000000',
	fontTitleSize: 10,
	fontTextSize: 5,
	image: '',
	borderRadius: 0,
	boxShadowSizeX: 0,
	boxShadowSizeY: 0,
	boxShadowSize: 0,
	boxShadowColor: '#000000',
}
