const initialValues = {
	width: 30,
	height: 30,
	title: '',
	subTitle: '',
	text: '',
	backgroundColor: '#ffffff',
	backgroundImage: '',
	headerColor: '#ffffff',
	bodyColor: '#ffffff',
	titleColor: '#000000',
	subTitleColor: '#000000',
	textColor: '#000000',
	titleSize: 10,
	subTitleSize: 8,
	textSize: 5,
	image: '',
	widthImage: 10,
	heightImage: 10,
	borderRadiusImage: 0,
	borderRadius: 0,
	boxShadowSizeX: 0,
	boxShadowSizeY: 0,
	boxShadowSize: 0,
	boxShadowColor: '#000000',
}

export default initialValues
